[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions_local_demo.csv
test_ignore = *

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    -<*>
    +<ble_protocol.c>
    +<lock_logic.c>

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<teensy/>

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<teensy/>
