# Generated by Django 5.2.17 on 2026-09-24 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('hardware_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded'), ('revoked', 'Revoked')], default='offline', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('certificate_serial', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('region', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='active', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('status', models.CharField(default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LockerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_count', models.PositiveSmallIntegerField(default=2)),
                ('enrolled_count', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='core.locker')),
            ],
        ),
        migrations.CreateModel(
            name='LockTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.locker')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='core.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=16)),
                ('category', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.locker')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_alerts', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('available_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lockers', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=160)),
                ('employee_id', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyOverrideEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('reported_via', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
                ('alert_created', models.BooleanField(default=False)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.locker')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=24)),
                ('public_key_fingerprint', models.CharField(blank=True, max_length=128)),
                ('attestation_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='core.enrolleduser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=24)),
                ('actor_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=80)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('entry_hash', models.CharField(blank=True, max_length=128)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], max_length=16)),
                ('oidc_subject', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UnlockRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved_waiting_second_party', 'Approved / waiting'), ('presence_verifying', 'Verifying'), ('token_issued', 'Token issued'), ('actuated', 'Actuated'), ('rejected', 'Rejected'), ('otp_locked_out', 'OTP locked out'), ('expired', 'Expired'), ('aborted', 'Aborted')], default='pending_review', max_length=40)),
                ('reason', models.TextField()),
                ('admin_review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlock_requests', to='core.locker')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_unlocks', to='core.enrolleduser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_unlock_requests', to=settings.AUTH_USER_MODEL)),
                ('second_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_unlocks', to='core.enrolleduser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlock_requests', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SignedUnlockGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(max_length=128)),
                ('nonce', models.CharField(max_length=128, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('actuated_at', models.DateTimeField(blank=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.locker')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signed_grant', to='core.unlockrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ble_session_id', models.CharField(max_length=128)),
                ('authenticated_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.locker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.enrolleduser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to='core.unlockrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_salt', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.enrolleduser')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenge', to='core.unlockrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LockerEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.locker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_enrollments', to='core.enrolleduser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('locker', 'user'), name='unique_locker_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_site_name'),
        ),
        migrations.AddConstraint(
            model_name='enrolleduser',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_id'), name='unique_employee_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'admin_user'), name='unique_admin_tenant'),
        ),
        migrations.AddIndex(
            model_name='unlockrequest',
            index=models.Index(fields=['tenant', 'status', 'requested_at'], name='core_unlock_tenant__ea4db1_idx'),
        ),
    ]
